import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
  ],
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  developerGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developer-guide',
    },
  ],
  apiReferenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
  securitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'security',
    },
  ],
};

export default sidebars;
