// Constants directory
// Naming convention: SCREAMING_SNAKE_CASE

export const CONTOP_PAIRING_TOKEN = 'CONTOP_PAIRING_TOKEN';
export const GEMINI_API_KEY_STORAGE_KEY = 'GEMINI_API_KEY';
export const OPENAI_API_KEY_STORAGE_KEY = 'OPENAI_API_KEY';
export const ANTHROPIC_API_KEY_STORAGE_KEY = 'ANTHROPIC_API_KEY';
export const OPENROUTER_API_KEY_STORAGE_KEY = 'OPENROUTER_API_KEY';
